"""rename appointment_id to appointment_Id in bills

Revision ID: 0a34c27f7b98
Revises: c8b1d9ab9888
Create Date: 2026-04-17 20:50:45.366470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a34c27f7b98'
down_revision = 'c8b1d9ab9888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_Id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'appointment', ['appointment_Id'], ['appointment_Id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['User_ID'])

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user'), 'users', ['User_ID'], ['User_ID'], ondelete='CASCADE')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('notes')
        batch_op.drop_column('appointment_Id')

    # ### end Alembic commands ###
