"""Updated treatment catalogue schema

Revision ID: 18ca87fddf3e
Revises: bb464653eda3
Create Date: 2026-04-18 14:53:00.628264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ca87fddf3e'
down_revision = 'bb464653eda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_catalogue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('treatment_catalogue_dept_Id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'department', ['dept_id'], ['dept_Id'])
        batch_op.drop_column('dept_Id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_catalogue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_Id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('treatment_catalogue_dept_Id_fkey'), 'department', ['dept_Id'], ['dept_Id'])
        batch_op.drop_column('dept_id')

    # ### end Alembic commands ###
