"""add slot_time, consultation_fee, payment_status

Revision ID: 340f98dc45ec
Revises: 18ca87fddf3e
Create Date: 2026-04-20 17:43:19.963714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340f98dc45ec'
down_revision = '18ca87fddf3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('consultation_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('consultation_fee')
        batch_op.drop_column('slot_time')

    # ### end Alembic commands ###
