"""added doctor leave table

Revision ID: 791d5d51d1f1
Revises: 5bf76ae55969
Create Date: 2026-05-08 21:41:39.725000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791d5d51d1f1'
down_revision = '5bf76ae55969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_leaves',
    sa.Column('leave_Id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doct_Id'], ),
    sa.PrimaryKeyConstraint('leave_Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_leaves')
    # ### end Alembic commands ###
