"""Updated treatment catalogue schema

Revision ID: bb464653eda3
Revises: 46c08eb4570a
Create Date: 2026-04-18 14:52:18.993749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb464653eda3'
down_revision = '46c08eb4570a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('doctor_dept_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('doctor_dept_id_fkey'), 'users', ['User_ID'], ['User_ID'], ondelete='CASCADE')

    # ### end Alembic commands ###
