"""initial migration

Revision ID: c8b1d9ab9888
Revises: 
Create Date: 2026-04-14 07:02:03.905466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b1d9ab9888'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'doctor', ['doct_Id'], ['doct_Id'])
        batch_op.create_foreign_key(None, 'patients', ['patient_Id'], ['patient_Id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['User_ID'])

    with op.batch_alter_table('bed', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ward', ['ward_No'], ['ward_No'])

    with op.batch_alter_table('bed_records', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'bed', ['bed_No'], ['bed_No'])
        batch_op.create_foreign_key(None, 'nurse', ['nurse_Id'], ['nurse_Id'])
        batch_op.create_foreign_key(None, 'helpers', ['helper_Id'], ['helper_Id'])
        batch_op.create_foreign_key(None, 'patients', ['patient_Id'], ['patient_Id'])

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patients', ['patient_Id'], ['patient_Id'])

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['User_ID'], ['User_ID'])
        batch_op.create_foreign_key(None, 'department', ['dept_Id'], ['dept_Id'])

    with op.batch_alter_table('helpers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['User_ID'], ['User_ID'])
        batch_op.create_foreign_key(None, 'department', ['dept_Id'], ['dept_Id'])

    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patients', ['patient_Id'], ['patient_Id'])
        batch_op.create_foreign_key(None, 'doctor', ['doct_Id'], ['doct_Id'])

    with op.batch_alter_table('nurse', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'department', ['dept_Id'], ['dept_Id'])
        batch_op.create_foreign_key(None, 'users', ['User_ID'], ['User_ID'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['User_ID'], ['User_ID'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'bills', ['bill_id'], ['bill_id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'department', ['dept_Id'], ['dept_Id'])

    with op.batch_alter_table('room_records', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'room', ['room_no'], ['room_No'])
        batch_op.create_foreign_key(None, 'helpers', ['helper_Id'], ['helper_Id'])
        batch_op.create_foreign_key(None, 'patients', ['patient_Id'], ['patient_Id'])
        batch_op.create_foreign_key(None, 'nurse', ['nurse_Id'], ['nurse_Id'])

    with op.batch_alter_table('staff_shifts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'nurse', ['nurse_Id'], ['nurse_Id'])
        batch_op.create_foreign_key(None, 'helpers', ['helper_Id'], ['helper_Id'])
        batch_op.create_foreign_key(None, 'doctor', ['doct_Id'], ['doct_Id'])

    with op.batch_alter_table('surgery_records', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patients', ['patient_Id'], ['patient_Id'])
        batch_op.create_foreign_key(None, 'helpers', ['helper_Id'], ['helper_Id'])
        batch_op.create_foreign_key(None, 'doctor', ['surgeon_Id'], ['doct_Id'])
        batch_op.create_foreign_key(None, 'room', ['room_no'], ['room_No'])
        batch_op.create_foreign_key(None, 'nurse', ['nurse_Id'], ['nurse_Id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['Role_ID'], ['id'])

    with op.batch_alter_table('ward', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'department', ['dept_Id'], ['dept_Id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ward', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('surgery_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('staff_shifts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('room_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('nurse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('helpers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bed_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bed', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
