"""removed unique constraint for email in users table

Revision ID: df314a7e34bc
Revises: 03a2fe00e772
Create Date: 2026-04-24 19:22:13.305428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df314a7e34bc'
down_revision = '03a2fe00e772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['dept_Name'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['transaction_id'])

    with op.batch_alter_table('treatment_catalogue', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['treatment_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_catalogue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
