"""added fee master table

Revision ID: 03a2fe00e772
Revises: 340f98dc45ec
Create Date: 2026-04-22 15:41:47.657750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a2fe00e772'
down_revision = '340f98dc45ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_master',
    sa.Column('fee_id', sa.Integer(), nullable=False),
    sa.Column('dept_Id', sa.Integer(), nullable=True),
    sa.Column('doct_Id', sa.Integer(), nullable=True),
    sa.Column('fee_type', sa.String(length=50), nullable=True),
    sa.Column('treatment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dept_Id'], ['department.dept_Id'], ),
    sa.ForeignKeyConstraint(['doct_Id'], ['doctor.doct_Id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment_catalogue.treatment_id'], ),
    sa.PrimaryKeyConstraint('fee_id')
    )
    op.create_table('bill_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=150), nullable=True),
    sa.Column('treatment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment_catalogue.treatment_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_items')
    op.drop_table('fee_master')
    # ### end Alembic commands ###
