"""Updated treatment catalogue schema

Revision ID: 46c08eb4570a
Revises: 0a34c27f7b98
Create Date: 2026-04-18 14:47:28.110560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c08eb4570a'
down_revision = '0a34c27f7b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('doctor_user_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('treatment_catalogue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_Id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('default_cost', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'department', ['dept_Id'], ['dept_Id'])
        batch_op.drop_column('description')
        batch_op.drop_column('cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_catalogue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('default_cost')
        batch_op.drop_column('category')
        batch_op.drop_column('dept_Id')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('doctor_user_id_fkey'), 'users', ['User_ID'], ['User_ID'], ondelete='CASCADE')

    # ### end Alembic commands ###
