"""add leave approval fields

Revision ID: 67cbc471d052
Revises: d2c1f2737425
Create Date: 2026-05-11 22:03:18.627076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cbc471d052'
down_revision = 'd2c1f2737425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['approved_by'], ['User_ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_leaves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approved_on')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
